### ISSUE TITLE
[IMPORTANT] Invoice fails but transaction still proceeds

### ISSUE THREAD

**Issue by Hacker00025** [seyone22/seller#18]
![image](https://github.com/user-attachments/assets/4095395b-d0c0-4eb5-a4ed-1c69f5e8c6d2)
![image](https://github.com/user-attachments/assets/ffdf23dc-0492-4b68-b4b7-aeda7b9e17e2)

I broke the connection with the mail server and tried posting an invoice, but sure enough, the email failed. However, in the back end, the transaction was recorded. This should not happen, if the email fails to post then the transaction should also fail and not proceed any further till the connection is restored. No Entry should be in the sales data unless the email is also sent out

**Comment by seyone22** [comment]
Fixed by using database transaction to push to dB only after email sends
